import { db } from "@workspace/db";
import {
  onboardingChecklistsTable,
  claimsTable,
  settlementRecordsTable,
  driverFeedbackTable,
} from "@workspace/db";
import { sql } from "drizzle-orm";
import { logger } from "./lib/logger";

export async function seedDemoDataIfEmpty() {
  try {
    const [{ count }] = await db
      .select({ count: sql<number>`count(*)::int` })
      .from(onboardingChecklistsTable);
    if (count > 0) return;

    logger.info("Demo tables empty — seeding production with demo data");

    await db.insert(onboardingChecklistsTable).values([
      { facilityId: 1, coiSubmitted: true, coiVerified: true, contractSigned: true, taxStatusVerified: true, articlesOfIncorporationVerified: true, driversLicenseRequirementsVerified: true, vehicleInspectionComplete: true, telematicsAgreementSigned: true, telematicsDeviceInstalled: true, backgroundChecksPassed: true, notes: "All documentation received and verified. Ready for full network deployment.", assignedRepName: "Marcus Webb", completedAt: new Date("2026-01-15T09:00:00Z") },
      { facilityId: 2, coiSubmitted: true, coiVerified: true, contractSigned: true, taxStatusVerified: true, articlesOfIncorporationVerified: true, driversLicenseRequirementsVerified: true, vehicleInspectionComplete: true, telematicsAgreementSigned: true, telematicsDeviceInstalled: true, backgroundChecksPassed: true, notes: "Smooth onboarding. Exemplary compliance team on site.", assignedRepName: "Marcus Webb", completedAt: new Date("2026-01-22T11:00:00Z") },
      { facilityId: 3, coiSubmitted: true, coiVerified: true, contractSigned: true, taxStatusVerified: true, articlesOfIncorporationVerified: false, driversLicenseRequirementsVerified: true, vehicleInspectionComplete: false, telematicsAgreementSigned: true, telematicsDeviceInstalled: true, backgroundChecksPassed: false, notes: "Waiting on updated articles of incorporation after ownership change. 2 drivers still need CDL upgrade.", assignedRepName: "Diana Cho" },
      { facilityId: 4, coiSubmitted: true, coiVerified: true, contractSigned: true, taxStatusVerified: false, articlesOfIncorporationVerified: false, driversLicenseRequirementsVerified: false, vehicleInspectionComplete: false, telematicsAgreementSigned: true, telematicsDeviceInstalled: false, backgroundChecksPassed: false, notes: "New hauler. Tax documents pending IRS verification. Vehicle inspection scheduled for next week.", assignedRepName: "Marcus Webb" },
      { facilityId: 5, coiSubmitted: true, coiVerified: false, contractSigned: true, taxStatusVerified: true, articlesOfIncorporationVerified: true, driversLicenseRequirementsVerified: true, vehicleInspectionComplete: true, telematicsAgreementSigned: true, telematicsDeviceInstalled: true, backgroundChecksPassed: true, notes: "COI verified but limits below AAA threshold. Working with broker to adjust.", assignedRepName: "Diana Cho" },
      { facilityId: 6, coiSubmitted: true, coiVerified: true, contractSigned: true, taxStatusVerified: true, articlesOfIncorporationVerified: true, driversLicenseRequirementsVerified: true, vehicleInspectionComplete: true, telematicsAgreementSigned: true, telematicsDeviceInstalled: true, backgroundChecksPassed: true, notes: "Largest facility in network. All requirements exceeded minimum standards.", assignedRepName: "Sarah Patel", completedAt: new Date("2026-02-01T14:00:00Z") },
      { facilityId: 7, coiSubmitted: false, coiVerified: false, contractSigned: false, taxStatusVerified: false, articlesOfIncorporationVerified: false, driversLicenseRequirementsVerified: false, vehicleInspectionComplete: false, telematicsAgreementSigned: false, telematicsDeviceInstalled: false, backgroundChecksPassed: false, notes: "New application received. Kickoff call scheduled for next week.", assignedRepName: "Sarah Patel" },
      { facilityId: 8, coiSubmitted: true, coiVerified: true, contractSigned: true, taxStatusVerified: true, articlesOfIncorporationVerified: true, driversLicenseRequirementsVerified: true, vehicleInspectionComplete: false, telematicsAgreementSigned: true, telematicsDeviceInstalled: true, backgroundChecksPassed: true, notes: "Vehicle inspection rescheduled twice. All other items complete.", assignedRepName: "Marcus Webb" },
      { facilityId: 9, coiSubmitted: true, coiVerified: true, contractSigned: true, taxStatusVerified: true, articlesOfIncorporationVerified: true, driversLicenseRequirementsVerified: true, vehicleInspectionComplete: true, telematicsAgreementSigned: true, telematicsDeviceInstalled: true, backgroundChecksPassed: true, notes: "Efficient onboarding. Fleet already telematics-equipped from prior carrier.", assignedRepName: "Diana Cho", completedAt: new Date("2026-03-10T10:00:00Z") },
    ]);

    await db.insert(claimsTable).values([
      { facilityId: 1, claimNumber: "CLM-2026-0041", claimantName: "Rivera, M.", driverId: 1, status: "open", coverageType: "Commercial Auto Liability", incidentDate: new Date("2026-04-12"), reportedDate: new Date("2026-04-12"), description: "Rear-end collision at traffic stop. Third-party vehicle sustained moderate damage. Dashcam footage captured.", reserveAmount: "28500", paidAmount: "0", tpaName: "Sedgwick", adjusterName: "Tom Hargrove", exonerated: false, resolutionNotes: null },
      { facilityId: 2, claimNumber: "CLM-2026-0038", claimantName: "Nguyen, P.", driverId: 3, status: "open", coverageType: "Commercial Auto Liability", incidentDate: new Date("2026-04-05"), reportedDate: new Date("2026-04-06"), description: "Sideswipe during lane change on highway. Minor property damage only. No injuries.", reserveAmount: "9800", paidAmount: "0", tpaName: "Sedgwick", adjusterName: "Lisa Monroe", exonerated: false, resolutionNotes: null },
      { facilityId: 3, claimNumber: "CLM-2026-0031", claimantName: "Thompson, D.", driverId: 5, status: "under_review", coverageType: "General Liability", incidentDate: new Date("2026-03-18"), reportedDate: new Date("2026-03-19"), description: "Customer property damaged during tow. Claimant disputing value. FleetLytics footage shows driver followed protocol.", reserveAmount: "15000", paidAmount: "0", tpaName: "Gallagher Bassett", adjusterName: "Ray Castillo", exonerated: false, resolutionNotes: "Dashcam review in progress — likely exoneration" },
      { facilityId: 4, claimNumber: "CLM-2026-0027", claimantName: "Baker, S.", driverId: 7, status: "closed", coverageType: "Commercial Auto Liability", incidentDate: new Date("2026-02-28"), reportedDate: new Date("2026-02-28"), description: "Backing accident in parking lot. Telematics confirmed low speed. Settled for nuisance value.", reserveAmount: "5000", paidAmount: "3200", tpaName: "Sedgwick", adjusterName: "Tom Hargrove", exonerated: false, resolutionNotes: "Settled. Telematics data reduced liability exposure." },
      { facilityId: 5, claimNumber: "CLM-2026-0019", claimantName: "Martinez, J.", driverId: 9, status: "closed", coverageType: "Commercial Auto Liability", incidentDate: new Date("2026-02-01"), reportedDate: new Date("2026-02-02"), description: "Red-light violation led to T-bone collision. Dashcam confirmed third party ran light. Full exoneration achieved.", reserveAmount: "42000", paidAmount: "0", tpaName: "Gallagher Bassett", adjusterName: "Lisa Monroe", exonerated: true, resolutionNotes: "Full exoneration. Dashcam footage decisive. Third party at fault." },
      { facilityId: 6, claimNumber: "CLM-2026-0012", claimantName: "Davis, K.", driverId: 11, status: "closed", coverageType: "Workers Compensation", incidentDate: new Date("2026-01-14"), reportedDate: new Date("2026-01-15"), description: "Driver slip-and-fall during vehicle hookup in icy conditions. Medical treatment required.", reserveAmount: "18500", paidAmount: "16200", tpaName: "Sedgwick", adjusterName: "Ray Castillo", exonerated: false, resolutionNotes: "WC claim resolved. Preventive training added to fleet program." },
    ]);

    await db.insert(settlementRecordsTable).values([
      { facilityId: 1, periodStart: new Date("2026-04-01"), periodEnd: new Date("2026-04-30"), grossSettlement: "48200", premiumDeductionPct: "12.5", premiumDeductionAmount: "6025", netSettlement: "42175", deductionReason: "Quarterly premium installment — Commercial Auto Liability policy via Travelers", status: "paid", notes: "On-time payment. No disputes." },
      { facilityId: 2, periodStart: new Date("2026-04-01"), periodEnd: new Date("2026-04-30"), grossSettlement: "31500", premiumDeductionPct: "10.0", premiumDeductionAmount: "3150", netSettlement: "28350", deductionReason: "Quarterly premium installment — Commercial Auto policy via Canal Insurance", status: "paid", notes: "Deduction reflects improved fleet score — rate reduced from prior quarter." },
      { facilityId: 3, periodStart: new Date("2026-04-01"), periodEnd: new Date("2026-04-30"), grossSettlement: "22800", premiumDeductionPct: "14.2", premiumDeductionAmount: "3238", netSettlement: "19562", deductionReason: "Monthly premium — elevated rate due to open claim CLM-2026-0031", status: "pending", notes: "Rate will be re-evaluated once CLM-2026-0031 resolves." },
      { facilityId: 4, periodStart: new Date("2026-03-01"), periodEnd: new Date("2026-03-31"), grossSettlement: "19400", premiumDeductionPct: "11.8", premiumDeductionAmount: "2289", netSettlement: "17111", deductionReason: "Quarterly premium installment — Protective Insurance", status: "paid", notes: "Disputed deduction amount resolved in Alliant review." },
      { facilityId: 5, periodStart: new Date("2026-04-01"), periodEnd: new Date("2026-04-30"), grossSettlement: "41000", premiumDeductionPct: "9.5", premiumDeductionAmount: "3895", netSettlement: "37105", deductionReason: "Monthly premium — rate improved following exoneration on CLM-2026-0019", status: "paid", notes: "FleetLytics exoneration outcome directly reduced renewal rate by 2.3%." },
      { facilityId: 6, periodStart: new Date("2026-04-01"), periodEnd: new Date("2026-04-30"), grossSettlement: "67300", premiumDeductionPct: "8.0", premiumDeductionAmount: "5384", netSettlement: "61916", deductionReason: "Quarterly premium — preferred rate, fleet score 82/100", status: "paid", notes: "Lowest rate in AAA network. High fleet score driving carrier competition." },
      { facilityId: 7, periodStart: new Date("2026-04-01"), periodEnd: new Date("2026-04-30"), grossSettlement: "14200", premiumDeductionPct: "18.0", premiumDeductionAmount: "2556", netSettlement: "11644", deductionReason: "Monthly premium — new hauler surcharge; onboarding incomplete", status: "pending", notes: "Surcharge will be removed once onboarding checklist is complete." },
      { facilityId: 8, periodStart: new Date("2026-04-01"), periodEnd: new Date("2026-04-30"), grossSettlement: "38900", premiumDeductionPct: "11.0", premiumDeductionAmount: "4279", netSettlement: "34621", deductionReason: "Monthly premium — National Interstate policy", status: "paid", notes: "" },
      { facilityId: 9, periodStart: new Date("2026-04-01"), periodEnd: new Date("2026-04-30"), grossSettlement: "29700", premiumDeductionPct: "9.0", premiumDeductionAmount: "2673", netSettlement: "27027", deductionReason: "Quarterly premium — Great West Casualty; telematics adoption discount applied", status: "paid", notes: "Telematics adoption discount reduced premium 1.5% vs prior year." },
    ]);

    await db.insert(driverFeedbackTable).values([
      { driverId: 1, facilityId: 1, eventType: "hard_braking", severity: "moderate", triggeredAt: new Date("2026-05-28T14:23:00Z"), videoClipUrl: "https://fleetlytics.demo/clip/001", coachNotes: "Advised 3-second following distance rule. Driver acknowledged and completed micro-training module.", driverAcknowledged: true, acknowledgedAt: new Date("2026-05-28T16:00:00Z"), resolved: true, resolvedAt: new Date("2026-05-29T09:00:00Z") },
      { driverId: 2, facilityId: 1, eventType: "speeding", severity: "high", triggeredAt: new Date("2026-05-27T09:11:00Z"), videoClipUrl: "https://fleetlytics.demo/clip/002", coachNotes: "17 mph over posted limit on I-95. Second offense this quarter. Formal coaching session required.", driverAcknowledged: true, acknowledgedAt: new Date("2026-05-27T18:00:00Z"), resolved: false },
      { driverId: 3, facilityId: 2, eventType: "distracted_driving", severity: "high", triggeredAt: new Date("2026-05-29T07:45:00Z"), videoClipUrl: "https://fleetlytics.demo/clip/003", coachNotes: "Camera detected phone use. First offense. Sent distracted driving awareness module.", driverAcknowledged: false, resolved: false },
      { driverId: 4, facilityId: 2, eventType: "hard_braking", severity: "low", triggeredAt: new Date("2026-05-26T15:55:00Z"), videoClipUrl: null, coachNotes: "Single low-severity event. No action required beyond automated alert.", driverAcknowledged: true, acknowledgedAt: new Date("2026-05-26T17:30:00Z"), resolved: true, resolvedAt: new Date("2026-05-26T17:30:00Z") },
      { driverId: 5, facilityId: 3, eventType: "harsh_acceleration", severity: "moderate", triggeredAt: new Date("2026-05-25T11:20:00Z"), videoClipUrl: "https://fleetlytics.demo/clip/005", coachNotes: "Repeated harsh acceleration pattern. Fuel efficiency and vehicle wear counseling provided.", driverAcknowledged: true, acknowledgedAt: new Date("2026-05-25T14:00:00Z"), resolved: false },
      { driverId: 6, facilityId: 3, eventType: "seatbelt_violation", severity: "high", triggeredAt: new Date("2026-05-28T08:05:00Z"), videoClipUrl: "https://fleetlytics.demo/clip/006", coachNotes: "No seatbelt detected. Written warning issued. Required to complete safety video.", driverAcknowledged: true, acknowledgedAt: new Date("2026-05-28T10:00:00Z"), resolved: true, resolvedAt: new Date("2026-05-29T08:00:00Z") },
      { driverId: 7, facilityId: 4, eventType: "speeding", severity: "moderate", triggeredAt: new Date("2026-05-24T16:30:00Z"), videoClipUrl: "https://fleetlytics.demo/clip/007", coachNotes: "10 mph over in school zone. Immediate corrective conversation with supervisor.", driverAcknowledged: true, acknowledgedAt: new Date("2026-05-24T18:00:00Z"), resolved: true, resolvedAt: new Date("2026-05-25T08:00:00Z") },
      { driverId: 8, facilityId: 4, eventType: "hard_braking", severity: "low", triggeredAt: new Date("2026-05-29T12:45:00Z"), videoClipUrl: null, coachNotes: "Single event, wet road conditions. Contextually acceptable. No action.", driverAcknowledged: true, acknowledgedAt: new Date("2026-05-29T13:30:00Z"), resolved: true, resolvedAt: new Date("2026-05-29T13:30:00Z") },
      { driverId: 9, facilityId: 5, eventType: "distracted_driving", severity: "moderate", triggeredAt: new Date("2026-05-27T13:10:00Z"), videoClipUrl: "https://fleetlytics.demo/clip/009", coachNotes: "Eyes-off-road event detected. Coaching call completed. Driver showed strong improvement awareness.", driverAcknowledged: true, acknowledgedAt: new Date("2026-05-27T16:00:00Z"), resolved: true, resolvedAt: new Date("2026-05-28T09:00:00Z") },
      { driverId: 10, facilityId: 5, eventType: "harsh_acceleration", severity: "low", triggeredAt: new Date("2026-05-26T09:00:00Z"), videoClipUrl: null, coachNotes: "Minor event. Automated nudge sent via FleetLytics app.", driverAcknowledged: false, resolved: false },
      { driverId: 11, facilityId: 6, eventType: "speeding", severity: "moderate", triggeredAt: new Date("2026-05-23T17:45:00Z"), videoClipUrl: "https://fleetlytics.demo/clip/011", coachNotes: "12 mph over limit on rural highway. Coaching session completed. No prior history.", driverAcknowledged: true, acknowledgedAt: new Date("2026-05-24T09:00:00Z"), resolved: true, resolvedAt: new Date("2026-05-24T09:00:00Z") },
      { driverId: 12, facilityId: 6, eventType: "hard_braking", severity: "low", triggeredAt: new Date("2026-05-29T08:20:00Z"), videoClipUrl: null, coachNotes: "Low severity. Acknowledged automatically.", driverAcknowledged: true, acknowledgedAt: new Date("2026-05-29T09:00:00Z"), resolved: true, resolvedAt: new Date("2026-05-29T09:00:00Z") },
    ]);

    logger.info("Demo data seeded successfully");
  } catch (err) {
    logger.error({ err }, "Failed to seed demo data — continuing without seed");
  }
}
